# Generated by Django 5.1.5 on 2025-09-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image_data_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
