# Generated by Django 5.1.5 on 2025-09-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_chatmessage_image_data_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
